select * 
from customer
-- what is total revenue generated by male vs female customers?
Select gender,
sum(purchase_amount) as total_revune
from customer
group by gender
order by total_revune DESC

-- which customer used a discount but still spent more than the average purchase amount ?
 with  customer_avg  as
 (Select *
 from customer
 where discount_applied = 'Yes' and purchase_amount > ( select avg(purchase_amount) from customer)
 )
  select count(*)
  from customer_avg;

-- which are the top 5 products with the highest average review rating
 with avg_pp as 
 (
 select item_purchased,
 avg(review_rating) as avg_review
 from customer
 group by item_purchased
 order by avg_review DESC
 )
 select * 
 from avg_pp
 limit 5;

 --compare the average Purchase amount between standard and express shipping 
 select shipping_type,
 round(avg(purchase_amount),2) as avg_amount
 from customer
 where shipping_type in ('Standard','Express')
 group by shipping_type

 ---do subscribed customers spend more ? compare average spend and total revuene between subscribers and non-subcribers
Select 
count(customer_id),
subscription_status , 
Avg(purchase_amount) as purchased_amt_avg,
sum(purchase_amount) as total_revune
from customer
group by subscription_status

---which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased,
round(100 * SUM(case when discount_applied = 'Yes' Then 1 Else 0 End)/count(*),2) as Discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

---segment customers into new, returning , and loyal based on their total
----numner pf previous purchases, and show the count of each segment.
with customer_type as
(SELECT *,
    CASE
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'New'
        WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select 
customer_segment,
count(*)
from customer_type
group by customer_segment

---what is the top 3 most purchased products within each category ?
with items_counts as 
(
select category,
item_purchased,
count(customer_id) as total_order,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rnk
from  customer
group by category,item_purchased
)

SELECT *
FROM items_counts
where item_rnk <= 3;

---ae customer who are repeat buyers (more than 5 previous purchases  ) also likely to susbribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
group by subscription_status

--- revenue by age group 

Select age_group,
Sum(purchase_amount) as total_rev
from customer
group by age_group
order by total_rev desc;
